import { Bai_Jamjuree as BaiJamjuree } from 'next/font/google'
import './globals.css'

const bai = BaiJamjuree({
  subsets: ['latin'],
  variable: ['--font-bai'],
  weight: ['400', '600'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bai.variable} font-bai`}>{children}</body>
    </html>
  )
}
